name: Sync policies
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      # https://github.com/marketplace/actions/repo-file-sync-action
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1.19.1
        with:
          GH_PAT: ${{ secrets.FLOWZONE_TOKEN }}
          SKIP_PR: true
          COMMIT_EACH_FILE: false
          DRY_RUN: ${{ github.event_name == 'pull_request' }}
